// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using internship_entry_task.Repositories.Data.DataBaseContext;

#nullable disable

namespace internship_entry_task.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20250726154239_DataBaseFix")]
    partial class DataBaseFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("internship_entry_task.Models.GameModel", b =>
                {
                    b.Property<Guid>("gameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("conditions")
                        .HasColumnType("text");

                    b.Property<string>("currentPlayer")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasAnnotation("CheckConstraint", "currentPlayer IN ('X', 'O')");

                    b.Property<string>("gameField")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("moveNumber")
                        .HasColumnType("integer");

                    b.HasKey("gameId");

                    b.ToTable("Games", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
